Se agregan properties para los ambientes next, alfa y beta y se arreg…
ong-bitcoin-argentina/DIDI-SSI-Semillas-backend pull request #2
Opened 2021-03-19 13:22 UTC by lucas-mauro

MM-119 #time 1h #comment Se agregaron properties para los ambientes next, alfa y beta. Tambien se modifico las properties locales para poder levantar el proyecto y se arreglo swagger-ui cambiando su version.

2021-03-19 15:49 UTC, MatiasOS requested changes
Tenemos que cambiar unos detalles

2021-03-19 15:49 UTC, MatiasOS commented on src/main/resources/application-alfa.properties
> +didi.base_url=${DIDI_URL_ALFA}
Te pasé mal, es `alpha`! Cambia los otros también y el nombre del archivo profa

2021-03-19 15:49 UTC, MatiasOS commented on src/main/resources/application-beta.properties
> +didi.server.url=https://server.alpha.didi.org.ar/api/1.0/didi/
`https://server.beta.didi.org.ar/api/1.0/didi/`

2021-03-19 15:49 UTC, MatiasOS commented on src/main/resources/application-next.properties
> +didi.server.url=https://server.alpha.didi.org.ar/api/1.0/didi/
`https://server.next.didi.org.ar/api/1.0/didi/`

2021-03-19 15:49 UTC, MatiasOS commented on src/main/resources/application-beta.properties
> +frontend.url=https://semillas.didi.org.ar
`https://beta.semillas.didi.org.ar

2021-03-19 15:49 UTC, MatiasOS commented on src/main/resources/application-next.properties
> +frontend.url=https://semillas.didi.org.ar
`https://next.semillas.didi.org.ar`

2021-03-20 02:04 UTC, MatiasOS requested changes
Los cambios anteriores están bien! Solo unos más que no lo había visto.

2021-03-20 02:04 UTC, MatiasOS commented on src/main/resources/application-next.properties
> +mailgun.cc=antonela@programasemillas.com
En esta versión de pruebas, no hace falta enviar mail a Semillas. En todo caso, podemos recibirlos en DIDI para las pruebas

2021-03-20 02:04 UTC, MatiasOS commented on src/main/resources/application.properties
> +didi.base_url=https://issuer.api.staging.didi.atixlabs.com/api/1.0/didi_issuer/
Este debería ser `https://issuer.api.next.didi.org.ar/api/1.0/didi_issuer/`

2021-03-20 02:04 UTC, MatiasOS commented on src/main/resources/application.properties
>  didi.server.url=https://server.staging.didi.atixlabs.com/api/1.0/didi/
Este también debería ser https://issuer.api.next.didi.org.ar/api/1.0/didi_issuer/

2021-03-20 11:22 UTC, lucas-mauro commented on src/main/resources/application.properties
> +didi.base_url=https://issuer.api.staging.didi.atixlabs.com/api/1.0/didi_issuer/
estas peroperties son dummy

2021-03-22 15:04 UTC, MatiasOS approved these changes
:100:

2021-03-25 14:44 UTC, MatiasOS approved these changes
:+1:

2021-03-26 01:09 UTC, merged