Mm 151 - Check and update loans finalized and default with Bondarea
ong-bitcoin-argentina/DIDI-SSI-Semillas-backend pull request #9
Opened 2021-05-03 12:11 UTC by lucas-mauro

Implement a new check and update loans finalized and default with Bondarea. Add update of expiredAmount in finalized loans.

2021-05-03 13:05 UTC, MatiasOS requested changes

2021-05-03 13:05 UTC, MatiasOS commented on src/main/java/com/atixlabs/semillasmiddleware/app/bondarea/service/BondareaService.java
> +    public static final BigDecimal MAX_AMOUNT = BigDecimal.valueOf(500);
Este valor parece que no se vuelve a utilizar.

2021-05-03 13:05 UTC, MatiasOS commented on src/main/java/com/atixlabs/semillasmiddleware/app/bondarea/service/BondareaService.java
> +        //Update a PENDING the Loans that is actives and not was update by new loans of Bondarea.
Update to PENDING the Loans that are ACTIVE and wasn't updated by new loans of Bondarea.

2021-05-03 13:05 UTC, MatiasOS commented on src/main/java/com/atixlabs/semillasmiddleware/app/bondarea/service/BondareaService.java
> +                modifiedLoans.addAll(loanRepository.findAllByStatusAndState(LoanStatusCodes.FINALIZED.getCode(), LoanStateCodes.DEFAULT.getCode()));
Es necesario volver a realizar este **loanRepository.findAllByStatusAndState(** ?  Por lo que veo, dentro de **handleDefaultFinalizedLoans** no se modifica ni Status ni  State.

2021-05-03 14:35 UTC, lucas-mauro commented on src/main/java/com/atixlabs/semillasmiddleware/app/bondarea/service/BondareaService.java
> +                modifiedLoans.addAll(loanRepository.findAllByStatusAndState(LoanStatusCodes.FINALIZED.getCode(), LoanStateCodes.DEFAULT.getCode()));
En la linea 587 recupera los ultimos loans modificados y que esten activos para chequear si estan en default o no. En la linea 588 yo le sumo los finalizados y en default para que haga la misma actualizacion, de otra manera no los considera

2021-05-04 13:38 UTC, silviaox approved these changes

2021-05-04 23:27 UTC, MatiasOS approved these changes

2021-05-04 23:27 UTC, merged